# Generated by Django 4.0.4 on 2022-05-18 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка в сторе')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.CreateModel(
            name='AppPlatform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('base_store_link', models.TextField(verbose_name='Базовая ссылка на страницу поиска стора')),
            ],
            options={
                'verbose_name': 'Платформа приложения',
                'verbose_name_plural': 'Платформы приложений',
            },
        ),
        migrations.CreateModel(
            name='AppPositionScriptRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Старт')),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Завершился')),
            ],
            options={
                'verbose_name': 'Запуск скрипта (поиск позиций приложений)',
                'verbose_name_plural': 'Запуски скрипта',
            },
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('google_store_link_attributes', models.TextField(verbose_name='Аттрибуты для поиска в гугл сторе')),
                ('apple_store_link_attributes', models.TextField(verbose_name='Аттрибуты для поиска в эпл сторе')),
            ],
            options={
                'verbose_name': 'Тип приложения',
                'verbose_name_plural': 'Типы приложений',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('app_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.apptype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='DailyAggregatedPositionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateField(verbose_name='Дата')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.app', verbose_name='Приложение')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.keyword', verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Агрегированные данные по дням',
                'verbose_name_plural': 'Агрегированные данные по дням',
            },
        ),
        migrations.CreateModel(
            name='AppPositionScriptRunData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.app', verbose_name='Приложение')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.keyword', verbose_name='Ключевое слово')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.apppositionscriptrun', verbose_name='Запуск скрипта')),
            ],
            options={
                'verbose_name': 'Данные запуска скрипта',
                'verbose_name_plural': 'Данные запуска скрипта',
            },
        ),
        migrations.AddField(
            model_name='apppositionscriptrun',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.apptype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='app',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.apptype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='app',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.appplatform', verbose_name='Платформа'),
        ),
    ]
