# Generated by Django 4.1.5 on 2023-01-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активно'),
        ),
    ]
