# Generated by Django 4.1.5 on 2023-03-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0002_app_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='campaign_id',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='ID кампании в keitaro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_icons/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='app',
            name='num',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
