# Generated by Django 4.1.5 on 2023-03-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0004_keitarodailyappdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keitarodailyappdata',
            options={'verbose_name': 'Данные из keitaro', 'verbose_name_plural': 'Данные из keitaro'},
        ),
    ]
