# Generated by Django 4.1.5 on 2023-03-03 02:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0005_alter_keitarodailyappdata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='link',
        ),
        migrations.AddField(
            model_name='app',
            name='package_id',
            field=models.CharField(max_length=255, null=True, verbose_name='ID пакета'),
            preserve_default=False,
        ),
    ]
