# Generated by Django 4.1.5 on 2023-03-03 02:53
import builtins
from django.db import migrations, models

def gen_id(apps, schema_editor):
    MyModel = apps.get_model('kwfinder', 'App')
    for row in MyModel.objects.all():
        row.package_id = str(builtins.id(row))
        row.save(update_fields=['package_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0006_remove_app_link_app_package_id'),
    ]

    operations = [
        migrations.RunPython(gen_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='app',
            name='package_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID пакета', null=False),
            preserve_default=False,
        ),
    ]
