# Generated by Django 4.1.5 on 2023-03-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0008_asoworldregion_appplatform_asoworld_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptype',
            name='asoworld_region',
            field=models.ForeignKey(default='BR', on_delete=django.db.models.deletion.CASCADE, to='kwfinder.asoworldregion', verbose_name='Регион (ASO World)'),
            preserve_default=False,
        ),
    ]
