# Generated by Django 4.1.5 on 2023-03-10 07:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0009_apptype_asoworld_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASOWorldOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('asoworld_id', models.CharField(max_length=255, unique=True, verbose_name='ASO World id')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Completed'), (3, 'Invalid'), (4, 'Accounting'), (5, 'Canceled'), (6, 'Paused')], verbose_name='Статус')),
                ('submit_type', models.CharField(choices=[('PACKAGE', 'Package (Direct) Installs'), ('KEYWORD', 'Keyword Installs'), ('RATE', 'Ratings'), ('REVIEW', 'Reviews'), ('COMPOSITE', 'Advanced Campaign'), ('LREVIEW', 'App Review Likes Service'), ('GREVIEW', 'Guaranteed Reviews Service'), ('SMART', 'Smart Campaign'), ('INSTALLS', 'Combo Package')], max_length=9, verbose_name='Тип')),
                ('install_type', models.CharField(choices=[('24h', 'Spread Installs Within 24h'), ('once', 'All Installs At Once')], max_length=4, verbose_name='Тип установки')),
                ('order_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Создана')),
                ('started_at', models.DateTimeField(editable=False, verbose_name='Запущена')),
                ('canceled_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Отменена')),
                ('finished_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Закончена')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.app', verbose_name='Приложение')),
            ],
            options={
                'verbose_name': 'Заявка ASO World',
                'verbose_name_plural': 'Заявки ASO World',
            },
        ),
        migrations.CreateModel(
            name='ConsoleDailyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateField(verbose_name='Дата')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='Посетители')),
                ('installs', models.PositiveSmallIntegerField(default=0, verbose_name='Установки')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.app', verbose_name='Приложение')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.keyword', verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Данные из консоли',
                'verbose_name_plural': 'Данные из консоли',
            },
        ),
        migrations.CreateModel(
            name='ASOWorldOrderKeywordData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('installs', models.PositiveSmallIntegerField(default=0, verbose_name='Установки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('state', models.CharField(choices=[('0', 'Отработано'), ('1', 'В ожидании'), ('2', 'Отменено')], max_length=1, verbose_name='Статус')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.keyword', verbose_name='Ключевое слово')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.asoworldorder', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Установка по ключу в ASO World',
                'verbose_name_plural': 'Установки по ключу в ASO World',
            },
        ),
    ]
