# Generated by Django 4.1.7 on 2023-03-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0011_remove_asoworldorderkeyworddata_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='asoworldorder',
            name='last_paused_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Последняя пауза'),
        ),
    ]
