# Generated by Django 4.1.7 on 2023-03-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0012_asoworldorder_last_paused_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asoworldorder',
            old_name='order_price',
            new_name='price',
        ),
    ]
