# Generated by Django 4.1.7 on 2023-03-22 02:34

from django.db import migrations, models
import django.db.models.deletion


def regionsMatch(apps, schema_editor):
    App = apps.get_model("kwfinder", "App")
    Keyword = apps.get_model("kwfinder", "Keyword")

    db_alias = schema_editor.connection.alias
    for obj in App.objects.using(db_alias):
        obj.region = obj.app_type.asoworld_region
        obj.save()

    db_alias = schema_editor.connection.alias
    for obj in Keyword.objects.using(db_alias):
        obj.region = obj.app_type.asoworld_region
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0013_rename_order_price_asoworldorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='kwfinder.asoworldregion', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='asoworldregion',
            name='google_store_link_attributes',
            field=models.TextField(
                blank=True, null=True, verbose_name='Аттрибуты для поиска в гугл сторе'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='kwfinder.asoworldregion', verbose_name='Регион'),
        ),
        migrations.RunPython(regionsMatch)
    ]
