# Generated by Django 4.1.7 on 2023-03-22 02:51

from django.db import migrations, models


def setKeywordsToApps(apps, schema_editor):
    App = apps.get_model("kwfinder", "App")
    db_alias = schema_editor.connection.alias

    for app in App.objects.using(db_alias):
        app.keywords.set(app.app_type.keyword_set.using(db_alias).all())
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0014_app_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='keywords',
            field=models.ManyToManyField(to='kwfinder.keyword'),
        ),
        migrations.RunPython(setKeywordsToApps)
    ]
