# Generated by Django 4.1.7 on 2023-03-22 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0015_app_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='apppositionscriptrun',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='app_type',
        ),
        migrations.AlterField(
            model_name='app',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.asoworldregion', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwfinder.asoworldregion', verbose_name='Регион'),
        ),
        migrations.DeleteModel(
            name='AppType',
        ),
    ]
