# Generated by Django 4.1.7 on 2023-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0016_remove_app_app_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='keywords',
            field=models.ManyToManyField(to='kwfinder.keyword', verbose_name='Ключевые слова'),
        ),
    ]
