# Generated by Django 4.1.7 on 2023-03-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0017_alter_app_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asoworldregion',
            options={'ordering': ['code'], 'verbose_name': 'Регион (ASO World)', 'verbose_name_plural': 'Регионы (ASO World)'},
        ),
    ]
