# Generated by Django 4.1.7 on 2023-03-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0018_alter_asoworldregion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'permissions': (('can_see_all', 'Видит все приложения'),), 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
    ]
