# Generated by Django 4.1.7 on 2023-03-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwfinder', '0020_alter_keitarodailyappdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа приложений',
                'verbose_name_plural': 'Группы приложений',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kwfinder.appgroup', verbose_name='Группа'),
        ),
    ]
